apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sports-vision
data:
  APP_NAME: "Sports Vision Cloud"
  APP_VERSION: "1.0.0"
  DEBUG: "false"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DB: "sports_vision"
  INFLUX_URL: "http://influxdb-service:8086"
  INFLUX_ORG: "sports_vision"
  INFLUX_BUCKET: "training_data"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
